# Generated by Django 3.2 on 2021-04-17 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
