# Generated by Django 3.2 on 2021-04-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20210412_1613'),
        ('miltonblog', '0002_auto_20210417_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='description',
            field=models.TextField(verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='extendeds', to='photologue.Photo', verbose_name='foto portada'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='updated_on',
            field=models.DateField(auto_now=True, verbose_name='actualizado'),
        ),
    ]
