# Generated by Django 3.2 on 2021-04-17 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20210412_1613'),
        ('miltonblog', '0003_auto_20210417_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='photologue.gallery', verbose_name='Galeria'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Foto Portada'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='extendeds', to='photologue.Photo', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='updated_on',
            field=models.DateField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
