# Generated by Django 3.2 on 2021-04-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0005_auto_20210417_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='time',
        ),
    ]
