# Generated by Django 3.2 on 2021-04-18 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0006_remove_postimage_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postvideo',
            options={'verbose_name': 'Publicacion de video', 'verbose_name_plural': 'Publicaciones de videos'},
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='url',
        ),
        migrations.AddField(
            model_name='postvideo',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvideo',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvideo',
            name='image',
            field=models.FileField(blank=True, upload_to='videos/images/', verbose_name='Foto Portada'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvideo',
            name='updated_on',
            field=models.DateField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/', verbose_name='Video'),
            preserve_default=False,
        ),
    ]
