# Generated by Django 3.2 on 2021-04-18 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0007_auto_20210418_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='postvideo',
            name='mp4',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/mp4', verbose_name='Video mp4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvideo',
            name='webm',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/webm', verbose_name='Video webm'),
            preserve_default=False,
        ),
    ]
