# Generated by Django 3.2 on 2021-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0009_auto_20210418_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='mp4',
            field=models.FileField(blank='True', null=True, upload_to='videos/mp4', verbose_name='Video mp4'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='webm',
            field=models.FileField(blank='True', null=True, upload_to='videos/webm', verbose_name='Video webm'),
        ),
    ]
