# Generated by Django 3.2 on 2021-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0010_auto_20210418_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='mp4',
            field=models.TextField(blank='True', null=True, verbose_name='Video mp4'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='webm',
            field=models.TextField(blank='True', null=True, verbose_name='Video webm'),
        ),
    ]
