# Generated by Django 3.2 on 2021-04-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0011_auto_20210418_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvideo',
            name='image',
        ),
    ]
