# Generated by Django 3.2 on 2021-04-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0012_remove_postvideo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='title',
        ),
    ]
