# Generated by Django 3.2 on 2021-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0013_auto_20210423_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Titulo'),
        ),
    ]
