# Generated by Django 3.2 on 2021-04-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0014_auto_20210423_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, upload_to='images/', verbose_name='Foto Portada')),
            ],
            options={
                'verbose_name': 'Pdf',
                'verbose_name_plural': 'Pdfs',
            },
        ),
    ]
