# Generated by Django 3.2 on 2021-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonblog', '0017_alter_pdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='images/pdf', verbose_name='sonrisas'),
        ),
    ]
